language: node_js
node_js:
  - "10"
script:
  - npm install vuepress
  - mkdir .vuepress
  - vuepress build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: .vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
